# Generated by Django 2.2.3 on 2019-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tofu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
    ]
